### PR TITLE
Fix wrong wrong name in german translation.

### PR DESCRIPTION
**Pull request by ecsgh**

### CODE REVIEW

**Comment by Vogtinator** [comment]
The best way to contribute translation changes is by using https://l10n.opensuse.org

**Comment by ecsgh** [comment]
hmm. There is the right name. 
But not here in master.

**Comment by Vogtinator** [comment]
It seems like it was fixed a few hours ago, so it should be part of the next sync: https://l10n.opensuse.org/translate/desktop-file-translations/update-desktop-files-apps-master/de/?checksum=2dfb61203ec5a504#history

**Comment by lkocman** [comment]
Closing request

**Pull request closed without merging**
