### PR TITLE
Leap 15.6 desktop-file-translations

### PR DESCRIPTION
**Pull request by lkocman**
* Used by experimental 51-xml/download_data_from_download-o-o.sh from #13

### CODE REVIEW

**Comment by lkocman** [comment]
A log from "./generate_and_merge_pos.sh download" [generate_and_merge_pos_15.6.log](https://github.com/openSUSE/desktop-file-translations/files/13502331/generate_and_merge_pos_15.6.log)

**Comment by lkocman** [comment]
@stanislav-brabec @Vogtinator any review is highly welcome! Not sure if the tool didn't catch more data than we wanted.

**Comment by Vogtinator** [comment]
> @stanislav-brabec @Vogtinator any review is highly welcome! Not sure if the tool didn't catch more data than we wanted.

Possibly. IMO the appstream and polkit stuff can be deleted, it's not read. Not sure about mime data.

I checked a few files and couldn't spot anything obviously wrong, though the large amount of added lines is a bit suspicious.

**Comment by lkocman** [comment]
Oky @Vogtinator, let's not keep translators busy with thigs taht people don't read. I re-did the merge but with dropped appstream and polkit tarbals in downloads.

**Comment by lkocman** [comment]
Merging so we can proceed with translations.

**Pull request merged**
